services:

  database:
    container_name: postgres-local
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.database-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    user: root
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.pgadmin-data:/var/lib/pgadmin

  broker:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq
      - ./.rabbitmq-data/:/opt/definitions.json
      - ./.rabbitmq-data/:/etc/rabbitmq/rabbitmq.config

  rest-api:
    container_name: rest-api
    build:
      context: rest-api
      dockerfile: Dockerfile
    image: rest-api:v1
    ports:
      - 8080:8080
    depends_on:
      - database
      - pgadmin
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres

