services:

  database:
    container_name: postgres-local
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.database-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    user: root
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.pgadmin-data:/var/lib/pgadmin

  broker:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq
      - ./.rabbitmq-data/:/opt/definitions.json
      - ./.rabbitmq-data/:/etc/rabbitmq/rabbitmq.config

  rest-api:
    container_name: rest-api
    build:
      context: rest-api
      dockerfile: Dockerfile
    image: rest-api:v1
    ports:
      - 8080:8080
    depends_on:
      - database
      - pgadmin
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWIRD=postgres
      - SPRING_DATA_REST_BASE_PATH=api/v1

  telegram-bot-front:
    container_name: telegram-bot-front
    build:
      context: telegram-bot-front
      dockerfile: Dockerfile
    image: telegram-bot-front:v1
    ports:
      - 8081:8081
    depends_on:
      - broker
      - rest-api
    environment:
      - SERVER_PORT=8081
      - SPRING_RABBITMQ_HOST=rabbitmq
      - BOT_TOKEN=6706121039:AAEYJR8H-fIr8rx6sHJ7eETU3QotsD0K9SQ
      - BOT_NAME=Notes
      - BROKER_UPDATE_QUEUE=bot-update-queue
      - BROKER_SEND_MESSAGE_QUEUE=bot-send-message-queue

