services:

  database:
    container_name: postgres-local
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.database-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    user: root
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.pgadmin-data:/var/lib/pgadmin

  broker:
    image: rabbitmq:management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq

