spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  data:
    rest:
      detection-strategy: annotated
      return-body-on-create: true
      return-body-on-update: true
      base-path: api/v1
  jpa:
    open-in-view: false
    show-sql: true